/**
 * hook-registry.ts — Self-expanding hook pattern library
 *
 * Tracks every hook pattern the pipeline produces, correlates them with
 * performance outcomes, and dynamically ranks/expands the pool of available
 * hook strategies. The script-agent pulls from this registry to evolve its
 * creative output over time.
 *
 * Key mechanics:
 * 1. Every hook that scores 80+ in QA is catalogued with its pattern classification
 * 2. Approved/rejected decisions shift pattern confidence
 * 3. Post-publish metrics (when available) weight patterns by real virality
 * 4. Discovery patterns auto-expand the library with novel structures
 * 5. The registry caps at the top N performing patterns per category to stay focused
 */
import { z } from "zod";

// ─── Hook Pattern Types ─────────────────────────────────────────────────────

export const HOOK_CATEGORIES = [
  "fear",
  "curiosity",
  "social_proof",
  "controversy",
  "open_loop",
  "shock_stat",
  "challenge",
  "storytelling",
  "identity",        // "If you're a [type], this is for you"
  "urgency",         // "Before it's too late" / "They just announced"
  "contrarian",      // "Stop doing X" / "Nobody talks about this"
  "transformation",  // "I went from X to Y in Z days"
  "pov",             // POV / scenario hooks
  "question",        // Direct question hooks
  "authority",       // Expert/insider reveal
  "trending_sound",  // Audio-first hooks (platform-native)
] as const;

export type HookCategory = typeof HOOK_CATEGORIES[number];

export const HookEntrySchema = z.object({
  /** Unique ID */
  id: z.string(),
  /** The hook text template (may include [NICHE], [PRODUCT], [STAT] placeholders) */
  template: z.string().min(1).max(500),
  /** Primary emotional trigger category */
  category: z.enum(HOOK_CATEGORIES),
  /** Secondary categories (a hook can trigger multiple emotions) */
  secondaryCategories: z.array(z.enum(HOOK_CATEGORIES)).max(3).default([]),
  /** Source: where this pattern came from */
  source: z.enum(["pipeline_qa", "human_approved", "discovery", "seed", "performance_winner"]),
  /** Platform where it performed best (if known) */
  bestPlatform: z.string().optional(),
  /** Niche where it originated */
  originNiche: z.string().optional(),

  // ─── Performance Metrics ───────────────────────────────────────────────
  /** Times used in pipeline */
  timesUsed: z.number().nonnegative().default(0),
  /** Times the resulting video was approved by human */
  timesApproved: z.number().nonnegative().default(0),
  /** Times rejected */
  timesRejected: z.number().nonnegative().default(0),
  /** Average QA score when this pattern was used */
  avgQaScore: z.number().min(0).max(100).default(0),
  /** Average virality score from post-publish performance (0 = no data yet) */
  avgViralityScore: z.number().min(0).max(100).default(0),
  /** Number of published videos with performance data */
  performanceDataPoints: z.number().nonnegative().default(0),

  // ─── Computed Rankings ─────────────────────────────────────────────────
  /** Composite confidence score (0-100) combining approval rate + virality */
  confidenceScore: z.number().min(0).max(100).default(50),
  /** Trending direction: is this pattern getting better or worse over time? */
  trend: z.enum(["rising", "stable", "declining", "new"]).default("new"),
  /** Last time this pattern was used or updated */
  lastUsedAt: z.string().datetime().optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type HookEntry = z.infer<typeof HookEntrySchema>;

export const HookRegistrySchema = z.object({
  version: z.number().int().default(1),
  entries: z.array(HookEntrySchema).default([]),
  /** Total hooks ever generated by the pipeline (even below threshold) */
  totalHooksProcessed: z.number().nonnegative().default(0),
  /** Last time the registry was updated with new performance data */
  lastPerformanceSync: z.string().datetime().optional(),
  updatedAt: z.string().datetime(),
});
export type HookRegistry = z.infer<typeof HookRegistrySchema>;

// ─── Registry Operations ────────────────────────────────────────────────────

/**
 * Classify a hook into a category based on linguistic pattern matching.
 * This is a fast heuristic — not LLM-powered — so it runs inline without cost.
 */
export function classifyHook(hookText: string): { primary: HookCategory; secondary: HookCategory[] } {
  const lower = hookText.toLowerCase();
  const scores: Partial<Record<HookCategory, number>> = {};

  // Pattern matching rules (weighted keywords/structures)
  const rules: Array<{ category: HookCategory; patterns: RegExp[]; weight: number }> = [
    { category: "fear", patterns: [/don't|never|mistake|warning|risk|danger|avoid|ruining|losing/i], weight: 2 },
    { category: "curiosity", patterns: [/secret|what if|did you know|turns out|apparently|nobody.*(talks|knows)/i], weight: 2 },
    { category: "social_proof", patterns: [/everyone|million|went viral|trending|people are/i], weight: 2 },
    { category: "controversy", patterns: [/unpopular|hot take|controversial|nobody.*agree|fight me/i], weight: 2 },
    { category: "open_loop", patterns: [/wait until|you won't believe|watch till|the end|part \d/i], weight: 2 },
    { category: "shock_stat", patterns: [/\d+%|\d+ (million|billion|thousand)|studies show|research/i], weight: 2 },
    { category: "challenge", patterns: [/try this|can you|bet you|challenge|dare/i], weight: 2 },
    { category: "storytelling", patterns: [/story|happened|once|yesterday|i was|when i/i], weight: 2 },
    { category: "identity", patterns: [/if you('re| are)|for (those|people|anyone)|this is for/i], weight: 2 },
    { category: "urgency", patterns: [/today|just (dropped|announced)|before|hurry|limited/i], weight: 2 },
    { category: "contrarian", patterns: [/stop \w|quit|wrong|overrated|myth|lie|toxic|scam|right now/i], weight: 3 },
    { category: "transformation", patterns: [/went from|before.*after|used to|changed|transformed|results/i], weight: 2 },
    { category: "pov", patterns: [/pov|imagine|picture this|when you|that moment/i], weight: 2 },
    { category: "question", patterns: [/^\s*(what|how|where|when|do you|is it|can you|have you)\b/i], weight: 3 },
    { category: "authority", patterns: [/as a|expert|insider|years of|professional|industry/i], weight: 2 },
    { category: "trending_sound", patterns: [/audio|sound|song|duet|stitch/i], weight: 1 },
  ];

  for (const rule of rules) {
    for (const pattern of rule.patterns) {
      if (pattern.test(lower)) {
        scores[rule.category] = (scores[rule.category] ?? 0) + rule.weight;
      }
    }
  }

  // Sort by score
  const sorted = Object.entries(scores).sort(([, a], [, b]) => b - a);

  if (sorted.length === 0) {
    return { primary: "curiosity", secondary: [] }; // Default
  }

  const primary = sorted[0][0] as HookCategory;
  const secondary = sorted.slice(1, 4)
    .filter(([, score]) => score > 0)
    .map(([cat]) => cat as HookCategory);

  return { primary, secondary };
}

/**
 * Register a new hook from the pipeline output.
 * Only hooks scoring 80+ in QA are registered to keep the pool high-quality.
 */
export function registerHook(
  registry: HookRegistry,
  hook: {
    text: string;
    qaScore: number;
    platform: string;
    niche: string;
    source: HookEntry["source"];
  }
): HookRegistry {
  // Update total count regardless
  const updated = { ...registry, totalHooksProcessed: registry.totalHooksProcessed + 1 };

  // Only catalogue hooks scoring 80+
  if (hook.qaScore < 80) return updated;

  const classification = classifyHook(hook.text);

  // Check if a very similar hook template already exists (fuzzy dedup)
  const normalized = normalizeHookTemplate(hook.text);
  const existing = updated.entries.find((e) =>
    normalizeHookTemplate(e.template) === normalized
  );

  if (existing) {
    // Boost existing entry's usage count
    existing.timesUsed += 1;
    existing.avgQaScore = runningAverage(existing.avgQaScore, hook.qaScore, existing.timesUsed);
    existing.lastUsedAt = new Date().toISOString();
    existing.updatedAt = new Date().toISOString();
    return { ...updated, updatedAt: new Date().toISOString() };
  }

  // Create new entry
  const newEntry: HookEntry = {
    id: `hook_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
    template: hook.text,
    category: classification.primary,
    secondaryCategories: classification.secondary,
    source: hook.source,
    bestPlatform: hook.platform,
    originNiche: hook.niche,
    timesUsed: 1,
    timesApproved: 0,
    timesRejected: 0,
    avgQaScore: hook.qaScore,
    avgViralityScore: 0,
    performanceDataPoints: 0,
    confidenceScore: Math.round(hook.qaScore * 0.6), // Initial confidence from QA alone (60% weight before decisions/performance)
    trend: "new",
    lastUsedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  updated.entries.push(newEntry);
  updated.updatedAt = new Date().toISOString();
  return updated;
}

/**
 * Record a human approval/rejection decision against hooks in the registry.
 */
export function recordDecision(
  registry: HookRegistry,
  hookText: string,
  decision: "approved" | "rejected"
): HookRegistry {
  const normalized = normalizeHookTemplate(hookText);
  const entry = registry.entries.find((e) => normalizeHookTemplate(e.template) === normalized);
  if (!entry) return registry;

  if (decision === "approved") {
    entry.timesApproved += 1;
  } else {
    entry.timesRejected += 1;
  }

  entry.confidenceScore = computeConfidence(entry);
  entry.updatedAt = new Date().toISOString();
  registry.updatedAt = new Date().toISOString();
  return registry;
}

/**
 * Update hook entries with post-publish virality performance data.
 */
export function recordPerformance(
  registry: HookRegistry,
  hookText: string,
  viralityScore: number
): HookRegistry {
  const normalized = normalizeHookTemplate(hookText);
  const entry = registry.entries.find((e) => normalizeHookTemplate(e.template) === normalized);
  if (!entry) return registry;

  entry.performanceDataPoints += 1;
  entry.avgViralityScore = runningAverage(
    entry.avgViralityScore,
    viralityScore,
    entry.performanceDataPoints
  );
  entry.confidenceScore = computeConfidence(entry);
  entry.trend = computeTrend(entry);
  entry.updatedAt = new Date().toISOString();
  registry.updatedAt = new Date().toISOString();
  registry.lastPerformanceSync = new Date().toISOString();
  return registry;
}

/**
 * Import hook patterns from discovery analysis (auto-expand the library).
 * Patterns identified in viral content that aren't already in the registry
 * get added as "discovery" source with a baseline confidence.
 */
export function importFromDiscovery(
  registry: HookRegistry,
  discoveredPatterns: Array<{
    hookText: string;
    platform: string;
    niche: string;
    viewCount: number;
    engagementRate: number;
  }>
): HookRegistry {
  for (const pattern of discoveredPatterns) {
    // Only import hooks from videos with strong engagement
    if (pattern.engagementRate < 0.05) continue;

    const normalized = normalizeHookTemplate(pattern.hookText);
    const exists = registry.entries.find((e) => normalizeHookTemplate(e.template) === normalized);
    if (exists) continue;

    const classification = classifyHook(pattern.hookText);
    const estimatedQaScore = Math.min(95, 60 + pattern.engagementRate * 200);

    const newEntry: HookEntry = {
      id: `hook_disc_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
      template: pattern.hookText,
      category: classification.primary,
      secondaryCategories: classification.secondary,
      source: "discovery",
      bestPlatform: pattern.platform,
      originNiche: pattern.niche,
      timesUsed: 0,
      timesApproved: 0,
      timesRejected: 0,
      avgQaScore: estimatedQaScore,
      avgViralityScore: 0,
      performanceDataPoints: 0,
      confidenceScore: estimatedQaScore * 0.3, // Lower initial confidence for discovery
      trend: "new",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    registry.entries.push(newEntry);
  }

  registry.updatedAt = new Date().toISOString();
  return registry;
}

/**
 * Get the top-performing hook examples for a given category + platform.
 * Used by adaptive-prompt.ts to inject few-shot examples into the script agent.
 */
export function getTopHooks(
  registry: HookRegistry,
  opts: {
    category?: HookCategory;
    platform?: string;
    niche?: string;
    limit?: number;
    minConfidence?: number;
  } = {}
): HookEntry[] {
  const { category, platform, niche, limit = 5, minConfidence = 40 } = opts;

  let candidates = registry.entries.filter((e) => e.confidenceScore >= minConfidence);

  if (category) {
    candidates = candidates.filter(
      (e) => e.category === category || e.secondaryCategories.includes(category)
    );
  }
  if (platform) {
    candidates = candidates.filter(
      (e) => !e.bestPlatform || e.bestPlatform === platform
    );
  }
  if (niche) {
    candidates = candidates.filter(
      (e) => !e.originNiche || e.originNiche === niche
    );
  }

  // Sort by confidence (performance-weighted), then by recency
  return candidates
    .sort((a, b) => {
      const scoreDiff = b.confidenceScore - a.confidenceScore;
      if (Math.abs(scoreDiff) > 5) return scoreDiff;
      // Tie-break: prefer recently successful ones
      return (b.lastUsedAt ?? "").localeCompare(a.lastUsedAt ?? "");
    })
    .slice(0, limit);
}

/**
 * Get a distribution of categories to ensure variety in hook generation.
 * Returns suggested categories with weights for the next batch of scripts.
 */
export function suggestCategories(
  registry: HookRegistry,
  recentlyUsed: HookCategory[],
  count: number = 4
): Array<{ category: HookCategory; weight: number; reason: string }> {
  // Count performance by category
  const categoryPerformance: Record<string, { avgVirality: number; count: number }> = {};
  for (const entry of registry.entries) {
    if (!categoryPerformance[entry.category]) {
      categoryPerformance[entry.category] = { avgVirality: 0, count: 0 };
    }
    categoryPerformance[entry.category].count += 1;
    categoryPerformance[entry.category].avgVirality += entry.confidenceScore;
  }

  // Normalize averages
  for (const cat of Object.keys(categoryPerformance)) {
    if (categoryPerformance[cat].count > 0) {
      categoryPerformance[cat].avgVirality /= categoryPerformance[cat].count;
    }
  }

  // If no data exists, return a diverse seed set of categories
  if (Object.keys(categoryPerformance).length === 0) {
    const seedCategories: HookCategory[] = ["curiosity", "contrarian", "fear", "transformation", "question", "social_proof", "urgency", "pov"];
    return seedCategories
      .filter((c) => !recentlyUsed.includes(c))
      .slice(0, count)
      .map((c, i) => ({
        category: c,
        weight: 1 / count,
        reason: i === 0 ? "High-engagement default" : "Variety — exploring diverse hooks",
      }));
  }

  // Build suggestions: mix top performers + under-explored + variety
  const suggestions: Array<{ category: HookCategory; weight: number; reason: string }> = [];

  // Top 2 performers
  const topPerformers = Object.entries(categoryPerformance)
    .sort(([, a], [, b]) => b.avgVirality - a.avgVirality)
    .slice(0, 2);

  for (const [cat, perf] of topPerformers) {
    suggestions.push({
      category: cat as HookCategory,
      weight: 0.35,
      reason: `Top performer (avg confidence: ${Math.round(perf.avgVirality)})`,
    });
  }

  // 1 under-explored (least used, not recently used)
  const underExplored = HOOK_CATEGORIES
    .filter((c) => !recentlyUsed.includes(c) && !topPerformers.some(([tc]) => tc === c))
    .sort((a, b) => (categoryPerformance[a]?.count ?? 0) - (categoryPerformance[b]?.count ?? 0));

  if (underExplored.length > 0) {
    suggestions.push({
      category: underExplored[0],
      weight: 0.15,
      reason: "Under-explored — testing new territory",
    });
  }

  // 1 rising trend
  const risingEntries = registry.entries.filter((e) => e.trend === "rising");
  if (risingEntries.length > 0) {
    const risingCat = risingEntries[0].category;
    if (!suggestions.some((s) => s.category === risingCat)) {
      suggestions.push({
        category: risingCat,
        weight: 0.15,
        reason: "Rising trend — momentum building",
      });
    }
  }

  return suggestions.slice(0, count);
}

// ─── Internal Utilities ─────────────────────────────────────────────────────

/** Normalize hook text for fuzzy matching (remove punctuation, lowercase, collapse whitespace) */
function normalizeHookTemplate(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/** Running average without storing all values */
function runningAverage(current: number, newValue: number, count: number): number {
  return current + (newValue - current) / count;
}

/**
 * Compute confidence score:
 * - 40% from approval rate (approved / (approved + rejected))
 * - 30% from QA score
 * - 30% from real virality performance (if available)
 */
function computeConfidence(entry: HookEntry): number {
  const totalDecisions = entry.timesApproved + entry.timesRejected;
  const approvalRate = totalDecisions > 0
    ? entry.timesApproved / totalDecisions
    : 0.5; // Neutral if no decisions yet

  const qaComponent = entry.avgQaScore / 100;
  const approvalComponent = approvalRate;
  const viralityComponent = entry.performanceDataPoints > 0
    ? entry.avgViralityScore / 100
    : qaComponent; // Fall back to QA if no performance data

  return Math.round(
    (approvalComponent * 40 + qaComponent * 30 + viralityComponent * 30)
  );
}

/** Determine trend direction based on recent performance vs historical */
function computeTrend(entry: HookEntry): HookEntry["trend"] {
  if (entry.timesUsed < 3) return "new";
  if (entry.performanceDataPoints < 2) return "stable";

  // Simple heuristic: if confidence is above 65 and rising data points, it's rising
  if (entry.confidenceScore > 65 && entry.avgViralityScore > 60) return "rising";
  if (entry.confidenceScore < 35 || entry.avgViralityScore < 30) return "declining";
  return "stable";
}
