import { UGCTemplateSchema, type UGCTemplate, type Platform } from "@vvugc/shared-schema";

const timestamp = "2026-01-01T00:00:00.000Z";
type TemplateDefinition = Omit<UGCTemplate, "createdAt" | "updatedAt">;

const allShortFormPlatforms: Platform[] = ["tiktok", "youtube_shorts", "instagram_reels", "facebook"];

/** Declarative built-ins: each production format owns its creative instructions and QA bar. */
const definitions: TemplateDefinition[] = [
  { id: "testimonial", version: "1.0.0", name: "Testimonial", description: "A credible personal-result story for consideration-stage viewers.", category: "social proof", targetPlatforms: allShortFormPlatforms, recommendedDurationSec: 30, scriptStructure: ["personal result", "before/problem", "discovery moment", "concrete benefit", "credibility qualifier", "CTA"], hookPatterns: ["I did not expect this to change my ___", "If you are dealing with ___, this is what worked for me"], requiredInputs: ["productProfile"], optionalInputs: ["creatorProfile", "brandKit"], visualDirection: "Start on the creator's genuine result, then cut to a lived-in before state and a quiet proof moment.", cameraDirection: "Selfie confession for the hook; medium talking shot for the story; close-up only for product proof.", creatorDirection: "Speak as personal experience, use qualifiers, and avoid sounding like a spokesperson.", productPlacementDirection: "Reveal after the discovery moment; show use during the concrete benefit and CTA.", captionStyle: "clean", ctaPatterns: ["See whether it works for your routine.", "Learn more if this sounds like your problem."], forbiddenPatterns: ["unsupported claims", "guaranteed results", "everyone needs this", "generic empty hype"], qaRubric: ["personal result is specific", "credibility qualifier is present", "benefit is supported by product profile", "CTA is clear"], defaultVariants: ["warm", "direct"], active: true },
  { id: "unboxing", version: "1.0.0", name: "Unboxing", description: "A sensory first-impression format that turns product details into desire.", category: "product reveal", targetPlatforms: allShortFormPlatforms, recommendedDurationSec: 25, scriptStructure: ["package arrival", "first reaction", "product reveal", "tactile/product details", "use case", "CTA"], hookPatterns: ["This just arrived and the packaging is already ___", "Wait until you see what is inside this box"], requiredInputs: ["productProfile"], optionalInputs: ["creatorProfile", "brandKit"], visualDirection: "Use satisfying package-opening beats, macro detail shots, and a final real-world use shot.", cameraDirection: "Top-down opening shot, then alternating hand-held macro and over-the-shoulder framing.", creatorDirection: "React in the moment; name only details that are visible or in the product profile.", productPlacementDirection: "Keep the package and product label legible at reveal; show the product in hand before CTA.", captionStyle: "bold", ctaPatterns: ["Take a closer look at the full details.", "See the complete unboxing."], forbiddenPatterns: ["best thing ever", "guaranteed results", "generic empty hype"], qaRubric: ["package arrival is visible", "product reveal is distinct", "at least one tactile detail is named", "CTA follows a use case"], defaultVariants: ["satisfying", "curious"], active: true },
  { id: "tutorial", version: "1.0.0", name: "Tutorial", description: "A teach-by-doing format for showing an achievable product outcome.", category: "education", targetPlatforms: ["tiktok", "youtube_shorts", "instagram_reels"], recommendedDurationSec: 35, scriptStructure: ["problem statement", "step-by-step demonstration", "common mistake", "outcome", "CTA"], hookPatterns: ["Here is how I use this to solve ___", "Stop doing ___ before you try this instead"], requiredInputs: ["productProfile"], optionalInputs: ["creatorProfile", "brandKit"], visualDirection: "Make every step observable with numbered overlays and show the outcome only after the demonstration.", cameraDirection: "Stable overhead or tripod framing for steps; insert close-ups exactly when hands interact with the product.", creatorDirection: "Teach at a measured pace and separate a common mistake from the recommended method.", productPlacementDirection: "Keep the product in frame during each operational step, not only in the opening.", captionStyle: "clean", ctaPatterns: ["Save this for your next try.", "Learn the full method."], forbiddenPatterns: ["instant fix", "guaranteed results", "skip the instructions"], qaRubric: ["steps are ordered", "common mistake is actionable", "outcome follows the steps", "CTA is useful rather than pressured"], defaultVariants: ["expert", "beginner-friendly"], active: true },
  { id: "problem_solution", version: "1.0.0", name: "Problem / Solution", description: "A tension-led format that makes the product mechanism feel relevant.", category: "conversion", targetPlatforms: allShortFormPlatforms, recommendedDurationSec: 30, scriptStructure: ["painful situation", "escalation", "product introduction", "mechanism", "proof", "CTA"], hookPatterns: ["I was tired of ___ getting worse", "The frustrating part of ___ is nobody tells you this"], requiredInputs: ["productProfile"], optionalInputs: ["creatorProfile", "brandKit"], visualDirection: "Open on the friction, heighten it with a relatable detail, then transition cleanly to product use and proof.", cameraDirection: "Use a tighter, imperfect handheld shot for the problem and steadier product close-ups for the solution.", creatorDirection: "Name a real pain without over-dramatizing; explain the mechanism in plain language.", productPlacementDirection: "Introduce product only after the escalation, then show the stated mechanism and proof use.", captionStyle: "bold", ctaPatterns: ["See if this approach fits your situation.", "Learn more about how it works."], forbiddenPatterns: ["cures", "guaranteed results", "fear-based pressure"], qaRubric: ["pain escalates before product introduction", "mechanism comes from product profile", "proof is concrete", "CTA is non-coercive"], defaultVariants: ["empathetic", "punchy"], active: true },
  { id: "comparison", version: "1.0.0", name: "Comparison", description: "A balanced side-by-side evaluation that earns trust before recommending.", category: "consideration", targetPlatforms: ["tiktok", "youtube_shorts", "instagram_reels"], recommendedDurationSec: 40, scriptStructure: ["two alternatives", "evaluation criteria", "product advantage", "honest limitation", "recommendation", "CTA"], hookPatterns: ["I compared ___ so you do not have to", "Before you choose between these two options, watch this"], requiredInputs: ["productProfile"], optionalInputs: ["creatorProfile", "brandKit"], visualDirection: "Keep alternatives visually separated with simple labels, then show the recommended product in the deciding use case.", cameraDirection: "Locked split-screen or matched top-down shots so comparison criteria remain legible.", creatorDirection: "State the limitation plainly and frame the recommendation around fit, not universal superiority.", productPlacementDirection: "Show the selected product alongside an unlabeled alternative only where fair comparison is possible.", captionStyle: "minimal", ctaPatterns: ["Choose based on the criteria that matter to you.", "See the product details before deciding."], forbiddenPatterns: ["better than every competitor", "guaranteed results", "dishonest comparison"], qaRubric: ["two alternatives are clear", "criteria are explicit", "honest limitation is present", "recommendation is qualified"], defaultVariants: ["analytical", "friendly"], active: true },
  { id: "before_after", version: "1.0.0", name: "Before / After", description: "A qualified transformation story that shows process instead of making unsupported promises.", category: "demonstration", targetPlatforms: allShortFormPlatforms, recommendedDurationSec: 30, scriptStructure: ["starting state", "process", "result", "timeframe/qualification", "CTA"], hookPatterns: ["Here is my before and after using ___", "This is what changed after I kept doing ___"], requiredInputs: ["productProfile"], optionalInputs: ["creatorProfile", "brandKit"], visualDirection: "Use matched before/after framing and include at least one process shot that connects the two states.", cameraDirection: "Lock exposure and angle for before/after; use a time-lapse or cutaway for the process.", creatorDirection: "Describe the result as individual experience and state a real timeframe or qualification.", productPlacementDirection: "Show product use in the process, not as a detached beauty shot.", captionStyle: "bold", ctaPatterns: ["See whether this routine fits your goals.", "Learn more before you start."], forbiddenPatterns: ["guaranteed results", "overnight transformation", "unqualified before and after"], qaRubric: ["starting state and result are distinguishable", "process is shown", "timeframe or qualifier is present", "no universal promise"], defaultVariants: ["documentary", "motivating"], active: true },
  { id: "founder_story", version: "1.0.0", name: "Founder Story", description: "A mission-led origin story that connects customer insight to a product decision.", category: "brand story", targetPlatforms: ["tiktok", "youtube_shorts", "instagram_reels"], recommendedDurationSec: 45, scriptStructure: ["founder context", "customer problem", "why existing options failed", "product origin", "mission", "CTA"], hookPatterns: ["I started this because I kept seeing ___", "The reason we built this was not what you might think"], requiredInputs: ["productProfile", "brandVoice"], optionalInputs: ["creatorProfile", "brandKit"], visualDirection: "Pair direct-to-camera founder context with documentary-style product-origin details and customer-problem imagery.", cameraDirection: "Use a grounded eye-level founder shot, intercut with close-ups of early sketches, materials, or product use.", creatorDirection: "Speak with specific conviction, acknowledge tradeoffs, and never invent founder history when a creator profile is used.", productPlacementDirection: "Introduce the product at its origin beat and return to it during the mission and CTA.", captionStyle: "clean", ctaPatterns: ["See the story and the product behind it.", "Learn more about what we are building."], forbiddenPatterns: ["disrupting everything", "guaranteed results", "generic empty hype"], qaRubric: ["founder context is concrete", "existing options failure is explained", "origin connects to customer problem", "mission is distinct from CTA"], defaultVariants: ["founder-led", "mission-led"], active: true }
];

export const BUILTIN_UGC_TEMPLATES: UGCTemplate[] = definitions.map((definition) => UGCTemplateSchema.parse({ ...definition, createdAt: timestamp, updatedAt: timestamp }));
export function getUgcTemplate(id: string): UGCTemplate | undefined { return BUILTIN_UGC_TEMPLATES.find((template) => template.id === id && template.active); }

/** Deterministic contract check used after an LLM response and by dry-runs. */
export function validateTemplateScript(template: UGCTemplate | undefined, script: { hook: string; points: string[]; cta: string }): string[] {
  if (!template) return [];
  const errors: string[] = [];
  const expected = Math.max(0, template.scriptStructure.length - 2);
  if (!script.hook.trim()) errors.push("missing_hook");
  if (!script.cta.trim()) errors.push("missing_cta");
  if (script.points.length < expected) errors.push("template_missing_beats");
  const text = [script.hook, ...script.points, script.cta].join(" ").toLowerCase();
  for (const forbidden of template.forbiddenPatterns) if (text.includes(forbidden.toLowerCase())) errors.push("template_forbidden_pattern");
  return [...new Set(errors)];
}

export function templateCompatibility(template: UGCTemplate | undefined, platforms: Platform[], durationSec: number): string[] {
  if (!template) return [];
  const warnings: string[] = [];
  const unsupported = platforms.filter((platform) => !template.targetPlatforms.includes(platform));
  if (unsupported.length) warnings.push(`${template.name} is not optimized for ${unsupported.join(", ")}`);
  if (durationSec < template.recommendedDurationSec - 10 || durationSec > template.recommendedDurationSec + 15) warnings.push(`${template.name} works best around ${template.recommendedDurationSec}s`);
  return warnings;
}
